classes:
- system.linux.system.repo.tcp_salt
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.master.api
- system.salt.minion.ca.salt_master
- system.reclass.storage.salt
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_telemetry_cluster
- system.reclass.storage.system.stacklight_log_cluster
- system.reclass.storage.system.stacklight_monitor_cluster
- system.reclass.storage.system.stacklight_telemetry_cluster
- cluster.mcp10_ovs_dpdk
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: https://github.com/sgudz/mcp10.git
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    salt_master_host: ${_param:infra_config_address}
  reclass:
    storage:
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
        infra_kvm_node03:
          params:
            keepalived_vip_priority: 102
        openstack_telemetry_node01:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 100
        openstack_telemetry_node02:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 101
        openstack_telemetry_node03:
          params:
            linux_system_codename: xenial
            keepalived_vip_priority: 102
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
        stacklight_monitor_node01:
          classes:
          - system.grafana.client.single
          - system.kibana.client.single
        openstack_control_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_database_node01:
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_compute_node01:
          name: ${_param:openstack_compute_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node01_control_address}
            single_address: ${_param:openstack_compute_node01_single_address}
            tenant_address: ${_param:openstack_compute_node01_tenant_address}
        openstack_compute_node02:
          name: ${_param:openstack_compute_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node02_control_address}
            single_address: ${_param:openstack_compute_node02_single_address}
            tenant_address: ${_param:openstack_compute_node02_tenant_address}
        openstack_compute_node03:
          name: ${_param:openstack_compute_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            control_address: ${_param:openstack_compute_node03_control_address}
            single_address: ${_param:openstack_compute_node03_single_address}
            tenant_address: ${_param:openstack_compute_node03_tenant_address}
